import Head from 'next/head';
import Hero from '../components/sections/Hero';
import Instagram from '../components/sections/Instagram';
import Slider from '../components/sections/Slider';
import { SliderData } from '../components/sections/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='PAWSH Photography' message='Because our Fur Babies are photogenic too!' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}